{% set name = "meshpy" %}
{% set uname = "MeshPy" %}
{% set version = "2025.1.1" %}
{% set sha256 = "70fc707fe9ccd9e907b95a9271804b4dd02e77d60644f64a0384cbf9e6d5b86b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ uname }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ uname[0] }}/{{ uname }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps -v
    - echo src/cpp/tetgen-LICENSE >> doc/faq.rst
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
    - pybind11
    - meson-python
  run:
    - python
    - numpy

test:
  source_files:
    - test/*
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest test
  imports:
    - meshpy

about:
  home: https://github.com/inducer/meshpy
  license: MIT AND LicenseRef-Proprietary-Triangle AND AGPL-3.0-or-later
  license_file: doc/faq.rst
  summary: Triangular and Tetrahedral Mesh Generator
  description: |
    MeshPy offers quality triangular and tetrahedral mesh generation for
    Python. Meshes of this type are mainly used in finite-element
    simulation codes, but also have many other applications ranging from
    computer graphics to robotics.
  doc_url: https://documen.tician.de/meshpy
  dev_url: https://github.com/inducer/meshpy

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - mwtoews
